---
abstract: 'Fake module with a prereq that is a core module for testing CPANPLUS'
author:
  - 'Chris Williams <chris@bingosnet.co.uk>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  Test::More: 0.47
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.99'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: ACME-CPANPLUS-Module-With-Core-PreReq
no_index:
  directory:
    - inc
    - t
provides:
  ACME::CPANPLUS::Module::With::Core::PreReq:
    file: lib/ACME/CPANPLUS/Module/With/Core/PreReq.pm
    version: 0.04
requires:
  Config: 0
  Errno: 0
  perl: 5.6.0
resources:
  homepage: http://github.com/bingos/acme-cpanplus-module-with-core-prereq/tree
  license: http://dev.perl.org/licenses/
  repository: git://github.com/bingos/acme-cpanplus-module-with-core-prereq.git
version: 0.04
